### ISSUE TITLE
Cannot find module '@lerna/project'

### ISSUE THREAD

**Issue by stalinkay** [thierrymichel/cz-ccgls#3]
Great tool @thierrymichel but it's not working with the latest version of commitizen.

```
$ git cz --no-verify

cz-cli@4.2.4, cz-ccgls@0.3.4

Cannot find module '@lerna/project'
Require stack:
- /Volumes/Reanimation/Work/NWR/2016080801_hybrid_app/noop.js
````

**Comment by stalinkay** [comment]
I also can't use it as a global npm module, i.e. `npm install -g cz-ccgls`. It installs but doesn't show up as a command on the command line.

**Comment by thierrymichel** [comment]
Hi @stalinkay,

Thanks for using `cz-ccgls` (a very personal project that suits my tastes and colours 😁).
This [0.4.0 version](https://www.npmjs.com/package/cz-ccgls/v/0.4.0) should (not heavily tested) work better…

Do not hesitate if something goes wrong.
And happy commits!

**Comment by stalinkay** [comment]
@thierrymichel Thanks for the fix.
